from pathlib import Path
from typing import Optional


def generate_stub(src_file: str, pr_number: Optional[int] = None) -> tuple[str, str]:
    """Return (test_path, stub_content) for a source file with no coverage."""
    ext = Path(src_file).suffix.lower().lstrip(".")
    if ext == "py":
        return _python_stub(src_file, pr_number)
    return _playwright_stub(src_file, pr_number)


def _playwright_stub(src_file: str, pr_number: Optional[int]) -> tuple[str, str]:
    path = Path(src_file.replace("\\", "/"))
    stem = path.stem
    suffix = path.suffix  # includes the dot

    parts = path.parts
    src_roots = {"src", "app", "lib"}
    start = 1 if parts and parts[0] in src_roots else 0
    dir_parts = parts[start:-1]

    test_dir = "tests/" + "/".join(dir_parts) if dir_parts else "tests"
    test_path = f"{test_dir}/{stem}.spec{suffix}"
    import_path = "../" * (test_path.count("/")) + src_file

    pr_note = f" on PR #{pr_number}" if pr_number else ""
    content = f"""import {{ test, expect }} from '@playwright/test';
import {{ {stem} }} from '{import_path}';

// auto-generated by quality-orchestrator
// target: {src_file}{pr_note}

test.describe('{stem}', () => {{

  test('happy path', async () => {{
    // TODO: replace with real assertion
    const result = await {stem}(/* args */);
    expect(result).toBeDefined();
  }});

  test('handles invalid input', async () => {{
    await expect(
      {stem}(null)
    ).rejects.toThrow();
  }});

  test.todo('edge cases — fill in based on diff');
}});
"""
    return test_path, content


def _python_stub(src_file: str, pr_number: Optional[int]) -> tuple[str, str]:
    path = Path(src_file.replace("\\", "/"))
    stem = path.stem

    parts = path.parts
    src_roots = {"src", "app", "lib"}
    start = 1 if parts and parts[0] in src_roots else 0
    dir_parts = parts[start:-1]

    test_dir = "tests/" + "/".join(dir_parts) if dir_parts else "tests"
    test_path = f"{test_dir}/test_{stem}.py"

    module_path = ".".join(list(dir_parts) + [stem]) if dir_parts else stem
    pr_note = f" on PR #{pr_number}" if pr_number else ""

    content = f"""import pytest
# auto-generated by quality-orchestrator
# target: {src_file}{pr_note}
from {module_path} import *  # noqa: F401,F403


def test_{stem}_happy_path():
    # TODO: replace with real assertion
    pass


def test_{stem}_invalid_input():
    with pytest.raises(Exception):
        pass  # TODO: call with invalid args


# TODO: add edge cases based on diff
"""
    return test_path, content
